spring:
  application:
    name: product-service
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        confirmedOrderByProduct-out-0:
          destination: orders-in
        confirmedOrderByProduct-in-0:
          destination: orders-out
          group: product
      rabbit:
        bindings:
          confirmedOrderByProduct-out-0:
            producer:
              exchangeType: direct
              routingKeyExpression: '"#"'
server:
  port: ${PORT:8093}